# Generated by Django 4.2 on 2025-04-07 13:38

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("profiles", "0025_auto_20190711_0250"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="profile",
            options={"verbose_name": "Profile", "verbose_name_plural": "Profiles"},
        ),
        migrations.AlterModelOptions(
            name="profileimage",
            options={
                "verbose_name": "Profile Image",
                "verbose_name_plural": "Profile Images",
            },
        ),
        migrations.AlterField(
            model_name="profile",
            name="bio",
            field=models.TextField(max_length=500),
        ),
        migrations.AlterField(
            model_name="profile",
            name="birth_date",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="profile",
            name="body_type",
            field=models.CharField(
                choices=[
                    ("THIN", "Thin"),
                    ("AVERAGE", "Average"),
                    ("FIT", "Fit"),
                    ("MUSCULAR", "Muscular"),
                    ("A_LITTLE_EXTRA", "A Little Extra"),
                    ("CURVY", "Curvy"),
                ],
                default="AVERAGE",
                max_length=15,
            ),
        ),
        migrations.AlterField(
            model_name="profile",
            name="citylat",
            field=models.DecimalField(
                decimal_places=6, default=-2.0180319, max_digits=9
            ),
        ),
        migrations.AlterField(
            model_name="profile",
            name="citylong",
            field=models.DecimalField(
                decimal_places=6, default=52.5525525, max_digits=9
            ),
        ),
        migrations.AlterField(
            model_name="profile",
            name="education",
            field=models.CharField(
                choices=[
                    ("HIGH_SCHOOL", "High School"),
                    ("COLLEGE", "College"),
                    ("BACHELORS_DEGREE", "Bachelors Degree"),
                    ("MASTERS", "Masters"),
                    ("PHD_POST_DOCTORAL", "PhD / Post Doctoral"),
                ],
                default="HIGH_SCHOOL",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="profile",
            name="ethnicity",
            field=models.CharField(
                choices=[
                    ("WHITE", "White"),
                    ("ASIAN_INDIAN", "Asian: Indian"),
                    ("ASIAN_PAKISTANI", "Asian: Pakistani"),
                    ("ASIAN_BANGLADESHI", "Asian: Bangladeshi"),
                    ("ASIAN_CHINESE", "Asian: Chinese"),
                    ("BLACK", "Black"),
                    ("MIXED", "Mixed"),
                    ("OTHER_ETHNICITY", "Other Ethnicity"),
                ],
                default="WHITE",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="profile",
            name="hair_length",
            field=models.CharField(
                choices=[
                    ("LONG", "Long"),
                    ("SHOULDER_LENGTH", "Shoulder Length"),
                    ("AVERAGE", "Average"),
                    ("SHORT", "Short"),
                    ("SHAVED", "Shaved"),
                ],
                default="LONG",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="profile",
            name="height",
            field=models.DecimalField(
                decimal_places=2,
                default=180.34,
                max_digits=5,
                validators=[
                    django.core.validators.MinValueValidator(100.0),
                    django.core.validators.MaxValueValidator(250.0),
                ],
            ),
        ),
        migrations.AlterField(
            model_name="profile",
            name="is_verified",
            field=models.CharField(
                choices=[
                    ("TO_BE_APPROVED", "To be approved"),
                    ("APPROVED", "Approved"),
                    ("NOT_APPROVED", "Not approved"),
                ],
                default="TO_BE_APPROVED",
                max_length=14,
            ),
        ),
        migrations.AlterField(
            model_name="profile",
            name="location",
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name="profile",
            name="relationship_status",
            field=models.CharField(
                choices=[
                    ("NEVER_MARRIED", "Never Married"),
                    ("DIVORCED", "Divorced"),
                    ("WIDOWED", "Widowed"),
                    ("SEPARATED", "Separated"),
                ],
                default="NEVER_MARRIED",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="profile",
            name="user",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="profile",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="profileimage",
            name="is_verified",
            field=models.CharField(
                choices=[
                    ("TO_BE_APPROVED", "To be approved"),
                    ("APPROVED", "Approved"),
                    ("NOT_APPROVED", "Not approved"),
                ],
                default="TO_BE_APPROVED",
                max_length=14,
            ),
        ),
        migrations.AlterField(
            model_name="profileimage",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="profile_images",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
