# Generated by Django 4.2 on 2025-05-25 19:25

from django.db import migrations, models
import profiles.models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0027_alter_profile_id_alter_profileimage_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profileimage',
            name='image',
            field=models.ImageField(blank=True, default='avatars/default_avt.png', upload_to=profiles.models.image_filename),
        ),
    ]
