# Generated by Django 4.2 on 2025-05-25 21:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0028_alter_profileimage_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='ethnicity',
        ),
        migrations.AlterField(
            model_name='profile',
            name='body_type',
            field=models.CharField(choices=[('THIN', 'Gầy'), ('AVERAGE', 'Trung bình'), ('FIT', 'Thon gọn'), ('MUSCULAR', 'Cơ bắp'), ('A_LITTLE_EXTRA', 'Hơi đầy đặn'), ('CURVY', 'Đẫy đà')], default='AVERAGE', max_length=15),
        ),
        migrations.AlterField(
            model_name='profile',
            name='education',
            field=models.CharField(choices=[('HIGH_SCHOOL', 'Trung học phổ thông'), ('COLLEGE', 'Cao đẳng'), ('BACHELORS_DEGREE', 'Cử nhân'), ('MASTERS', 'Thạc sĩ'), ('PHD_POST_DOCTORAL', 'Tiến sĩ / Sau tiến sĩ')], default='HIGH_SCHOOL', max_length=20),
        ),
        migrations.AlterField(
            model_name='profile',
            name='gender',
            field=models.CharField(choices=[('MALE', 'Nam'), ('FEMALE', 'Nữ')], default='MALE', max_length=6),
        ),
        migrations.AlterField(
            model_name='profile',
            name='hair_colour',
            field=models.CharField(choices=[('BLACK', 'Đen'), ('BLONDE', 'Vàng'), ('BROWN', 'Nâu'), ('RED', 'Đỏ'), ('GREY', 'Xám'), ('BALD', 'Hói'), ('BLUE', 'Xanh dương'), ('PINK', 'Hồng'), ('GREEN', 'Xanh lá'), ('PURPLE', 'Tím'), ('OTHER', 'Khác')], default='BLACK', max_length=10),
        ),
        migrations.AlterField(
            model_name='profile',
            name='hair_length',
            field=models.CharField(choices=[('LONG', 'Dài'), ('SHOULDER_LENGTH', 'Dài tới vai'), ('AVERAGE', 'Trung bình'), ('SHORT', 'Ngắn'), ('SHAVED', 'Cạo trọc')], default='LONG', max_length=20),
        ),
        migrations.AlterField(
            model_name='profile',
            name='is_verified',
            field=models.CharField(choices=[('TO_BE_APPROVED', 'Chờ phê duyệt'), ('APPROVED', 'Đã phê duyệt'), ('NOT_APPROVED', 'Không được phê duyệt')], default='TO_BE_APPROVED', max_length=14),
        ),
        migrations.AlterField(
            model_name='profile',
            name='looking_for',
            field=models.CharField(choices=[('MALE', 'Nam'), ('FEMALE', 'Nữ'), ('BOTH', 'Cả hai')], default='BOTH', max_length=6),
        ),
        migrations.AlterField(
            model_name='profile',
            name='relationship_status',
            field=models.CharField(choices=[('NEVER_MARRIED', 'Chưa từng kết hôn'), ('DIVORCED', 'Đã ly hôn'), ('WIDOWED', 'Góa'), ('SEPARATED', 'Ly thân')], default='NEVER_MARRIED', max_length=20),
        ),
    ]
