# Generated by Django 4.2 on 2025-05-10 17:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('chat', '0011_alter_conversations_id_alter_messages_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='winks',
            name='receiver',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='winks_receiver', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='winks',
            name='sender',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='winks_sender', to=settings.AUTH_USER_MODEL),
        ),
    ]
