# Generated by Django 4.2 on 2025-05-10 17:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('chat', '0012_alter_winks_receiver_alter_winks_sender'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reject',
            name='receiver',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rejected_received', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='reject',
            name='sender',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rejected_sender', to=settings.AUTH_USER_MODEL),
        ),
    ]
